package dependencies

object Versions {
    const val androidx_core = "1.7.0"
    const val androidx_appcompat = "1.4.1"
    const val androidx_constraint = "2.1.3"
    const val android_material_design = "1.5.0"

    const val kotlin = "1.8.0"
    const val detekt = "1.22.0"
    const val google_ksp = "1.8.0-1.0.9"
    const val koin = "3.3.2"
    const val koin_annotations = "1.1.1"
    const val gradle = "7.4.0"
    const val coroutines = "1.6.4"
    const val navigation = "2.4.1"
    const val google_services = "4.3.15"
    const val firebase_bom = "31.3.0"
    const val lifecycle = "2.4.0"
    const val room = "2.4.2"
    const val paging3 = "3.1.0"
    const val glide = "4.12.0"
    const val shimmer = "0.5.0"
    const val data_store = "1.0.0"
    const val ok_http_bom = "4.9.0"
    const val retrofit = "2.9.0"
    const val gson = "2.8.6"

    const val junit = "4.13.2"
    const val mockito_core = "4.2.0"
    const val mockito_kotlin = "2.2.0"
    const val androidx_junit = "1.1.3"
    const val androidx_core_testing = "2.1.0"
    const val androidx_espresso = "3.4.0"
    const val androidx_espresso_core = "3.4.0"
    const val fragment_testing = "1.5.5"
    const val androidx_test_runner = "1.4.0"
    const val androidx_test_orchestrator = "1.4.1"
    const val test_mock = "4.9.3"
}